//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int bookid { get; set; }
        public string start { get; set; }
        public string finish { get; set; }
    }
}
